import type { DemoState, InsuranceMetrics } from "./demoTypes";

export const AUTHORITY_TIERS = [
  {
    id: "tier-exec",
    name: "Executive" as const,
    description: "C-suite authority for high-value transactions and strategic decisions",
    approvalLimit: 5000000,
    escalationTo: undefined,
  },
  {
    id: "tier-mgr",
    name: "Manager" as const,
    description: "Department-level authority for operational approvals",
    approvalLimit: 250000,
    escalationTo: "Executive" as const,
  },
  {
    id: "tier-ops",
    name: "Operational" as const,
    description: "Day-to-day operational actions within defined limits",
    approvalLimit: 50000,
    escalationTo: "Manager" as const,
  },
];

const agents: DemoState["agents"] = [
  {
    id: "agent-treasury",
    name: "Treasury Agent",
    status: "Active",
    department: "Treasury",
    framework: "Custom",
    risk: "Critical",
    authorityTier: "Executive",
    permissions: "Cross-Border Transfers",
    spendLimit: "$2,000,000",
    coverage: "—",
    decisions: 0,
    accuracy: "—",
    lastActivity: "—",
    complianceStatus: "Compliant",
  },
  {
    id: "agent-procurement",
    name: "Procurement Agent",
    status: "Active",
    department: "Procurement",
    framework: "OpenAI Agents",
    risk: "Medium",
    authorityTier: "Manager",
    permissions: "Vendor Management",
    spendLimit: "$250,000",
    coverage: "—",
    decisions: 0,
    accuracy: "—",
    lastActivity: "—",
    complianceStatus: "Compliant",
  },
  {
    id: "agent-payroll",
    name: "Payroll Agent",
    status: "Active",
    department: "HR",
    framework: "Claude",
    risk: "High",
    authorityTier: "Manager",
    permissions: "Payroll Disbursements",
    spendLimit: "$1,000,000",
    coverage: "—",
    decisions: 0,
    accuracy: "—",
    lastActivity: "—",
    complianceStatus: "Compliant",
  },
  {
    id: "agent-finance",
    name: "Finance Agent",
    status: "Active",
    department: "Finance",
    framework: "LangGraph",
    risk: "High",
    authorityTier: "Executive",
    permissions: "Full Treasury",
    spendLimit: "$500,000",
    coverage: "—",
    decisions: 0,
    accuracy: "—",
    lastActivity: "—",
    complianceStatus: "Compliant",
  },
  {
    id: "agent-vendor",
    name: "Vendor Approval Agent",
    status: "Active",
    department: "Procurement",
    framework: "LangGraph",
    risk: "Medium",
    authorityTier: "Operational",
    permissions: "Vendor Onboarding",
    spendLimit: "$100,000",
    coverage: "—",
    decisions: 0,
    accuracy: "—",
    lastActivity: "—",
    complianceStatus: "Compliant",
  },
];

export function createEmptyInsuranceMetrics(): InsuranceMetrics {
  return {
    score: 0,
    governanceCoverage: 0,
    controlEffectiveness: 0,
    authorityCoverage: 0,
    evidenceIntegrity: 0,
    approvalCompliance: 0,
    policyEnforcement: 0,
    governedDecisions: 0,
    riskReduction: 0,
    riskLabel: "NOT ASSESSED",
  };
}

export function createInitialDemoState(): DemoState {
  return {
    agents,
    policies: [],
    intercepts: [],
    approvals: [],
    evidence: [],
    timeline: [],
    documents: [],
    authorityTiers: AUTHORITY_TIERS,
    insurance: createEmptyInsuranceMetrics(),
    idCounters: {
      decision: 0,
      approval: 0,
      evidence: 0,
      timeline: 0,
    },
  };
}
