"""reviewer_id as free text not uuid fk

Revision ID: 334dcaaa2a87
Revises: d1f41ef42ccd
Create Date: 2026-07-04 19:31:11.874143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '334dcaaa2a87'
down_revision: Union[str, Sequence[str], None] = 'd1f41ef42ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorities', 'reviewer_id',
               existing_type=sa.UUID(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('authorities', 'reviewer_id',
               existing_type=sa.Text(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
